# This workflow will build a release-like distribution when manually dispatched

name: Build

on:
  push:
    branches: ['publish']
  pull_request:
    branches: ['publish']
  workflow_dispatch:

permissions: write-all

jobs:
  build_apworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zip
        run: |
          pushd worlds
          zip -r -9 ../sc2.apworld sc2/ -x sc2/__pycache__/\* sc2/test/\*
          popd
      - name: Push Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sc2.apworld
          path: sc2.apworld
          retention-days: 7
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/publish' }}
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          upload_url: https://uploads.github.com/repos/MatthewMarinets/Archipelago/releases/250464423/assets{?name,label}
          release_id: 250464423
          asset_path: ./sc2.apworld
          asset_name: sc2.apworld
          asset_content_type: application/zip
